# Generated by Django 4.2.5 on 2023-09-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_test_text_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
